export const personagens = [
  "Naruto",
  "Sasuke",
  "Sakura",
  "Kakashi",
  "Gai",
  "Itachi",
  "Kisame",
  "Asuma",
  "Pain",
  "Orochimaru",
  "RockLee",
  "Sasori",
  "Deidara",
  "Neji",
  "Jiraya",
  "Hidan",
  "Hinata",
  "KillerBee",
  "Obito",
  "Shikamaru",
  "Hashirama",
  "Madara",
  "Tobirama",
  "Minato",
  "Gaara",
  "Kakuzu",
  "Konan",
  "Shisui",
];

export const imagens = {
  Naruto: "./IMG/Personagens/P_Naruto.png",
  Sasuke: "./IMG/Personagens/P_Sasuke.png",
  Sakura: "./IMG/Personagens/P_Sakura.png",
  Pain: "./IMG/Personagens/P_Pain.png",
  Gai: "./IMG/Personagens/P_Gai.png",
  Kakashi: "./IMG/Personagens/P_Kakashi.png",
  Itachi: "./IMG/Personagens/P_Itachi.png",
  Asuma: "./IMG/Personagens/P_Asuma.png",
  Orochimaru: "./IMG/Personagens/P_Orochimaru.png",
  Kisame: "./IMG/Personagens/P_Kisame.jpg",
  Random: "./IMG/Personagens/P_Random.jpg",
  Deidara: "./IMG/Personagens/P_Deidara.png",
  Sasori: "./IMG/Personagens/P_Sasori.png",
  RockLee: "./IMG/Personagens/P_RockLee.jpg",
  Jiraya: "./IMG/Personagens/P_Jiraya.png",
  Neji: "./IMG/Personagens/P_Neji.png",
  Hidan: "./IMG/Personagens/P_Hidan.png",
  Hinata: "./IMG/Personagens/P_Hinata.png",
  KillerBee: "./IMG/Personagens/P_KillerBee.png",
  Obito: "./IMG/Personagens/P_Obito.png",
  Shikamaru: "./IMG/Personagens/P_Shikamaru.png",
  Hashirama: "./IMG/Personagens/P_Hashirama.png",
  Madara: "./IMG/Personagens/P_Madara.png",
  Tobirama: "./IMG/Personagens/P_Tobirama.png",
  Minato: "./IMG/Personagens/P_Minato.png",
  Gaara: "./IMG/Personagens/P_Gaara.png",
  Kakuzu: "./IMG/Personagens/P_Kakuzu.png",
  Konan: "./IMG/Personagens/P_Konan.png",
  Shisui: "./IMG/Personagens/P_Shisui.png",
};
